### ISSUE TITLE
fun.schedule generates an error on basic ranges.

### ISSUE THREAD

**Issue by mhbw** [evolvingwild/evolving-hockey#2]
fun.schedule in shiny_all_functions errors when given pretty basic ranges. 

example: 

fun.schedule("2019-01-02","2019-01-04")
Error in x$games : $ operator is invalid for atomic vectors
Called from: lapply(x, fun, ...)

I *believe* this is from the dcapply functions although I can't isolate it at this time.

**Comment by evolvingwild** [comment]
The `sc.scrape_schedule` function located in the EH_scraper_functions.R script has replaced the function you are trying to run.
