### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by hriihimaki** [evolvingwild/evolving-hockey#3]
The repository is missing a license. 

Although you said ([in Twitter](https://twitter.com/EvolvingWild/status/1184694558954852353)) that people can use your code, it would be best if the repository itself [includes a proper license](https://help.github.com/en/articles/adding-a-license-to-a-repository) / terms of use. 

"Making your GitHub project public is not the same as licensing your project. Public projects are covered by GitHub’s Terms of Service, which allows others to view and fork your project, but your work otherwise comes with no permissions.

**If you want others to use, distribute, modify, or contribute back to your project, you need to include an open source license**. For example, someone cannot legally use any part of your GitHub project in their code, even if it’s public, unless you explicitly give them the right to do so."

Source: https://opensource.guide/legal/

**Comment by evolvingwild** [comment]
Thank you for pointing this out to us. We've added a GPL 3 license to this repository.
