### ISSUE TITLE
2019 Post season game id's

### ISSUE THREAD

**Issue by alsgregory** [evolvingwild/evolving-hockey#5]
It appears as though there is an error scraping 2019 Playoff game id's. E.g.

Game ID: 2019030001
Match: Philly @ Boston
Date: 2nd August 2020

`sc.scrape_pbp(games = c(2019030001))`

Log: `2019030001...  ERROR : arguments imply differing number of rows: 1, 0 ... 2.5 sec`

**Comment by alsgregory** [comment]
This is caused by `attendance_vec` being `numeric(0)` rather than a `0`, within the `game_info` method.

**Comment by evolvingwild** [comment]
What version of R and the tidyverse are you using? The scraper is only current through R version 3.6.2, tidyverse 1.3.0, and dply 0.8.3. I believe this is an issue that we will have to fix once we update to R 4.0 and/or dplyr version 1.0.x. We will be doing that soon hopefully.

**Comment by evolvingwild** [comment]
After updating to R version 4.0.2 and dplyr version 1.0.2, I have been unable to recreate the error you displayed. I'm going to close this issue for now - please open another issue if the issue persists.
